FROM python:3.12.9

WORKDIR /app

# Копируем файлы requirements.txt
COPY backend/requirements.txt /app/requirements.txt

# Устанавливаем зависимости Python
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "backend/app.py"]